### ISSUE TITLE
Example in readme gives an error

### ISSUE THREAD

**Issue by ncarchedi** [datacamp/dbconnectr#1]
I was able to do everything expect the last line of the example, which gave this error:

```r
> get_docs('main_app')
Fetching /dbconnect/main_app/docs from EC2 parameter store

An error occurred (ParameterNotFound) when calling the GetParameter operation: Parameter /dbconnect/main_app/docs not found.
Error: parse error: premature EOF
                                       
                     (right here) ------^
In addition: Warning message:
running command ''aws' ssm get-parameter --with-decryption --name /dbconnect/main_app/docs' had status 255 
```

**Comment by filipsch** [comment]
@ncarchedi very weird, for me there is no issue. 

```
> library(dbconnectr)
> get_docs("challenges-app")
Fetching /dbconnect/challenges-app/docs from EC2 parameter store
Opening database documentation...
> get_docs("main-app")
Fetching /dbconnect/main-app/docs from EC2 parameter store
Opening database documentation...
```

Does the issue still happen, also after you installed the latest version of the package? If yes, can you do `cat ~/.aws/credentials` in the terminal, and check if the AWS keys are properly set?

**Comment by dgrtwo** [comment]
This is because of the aws-cli version (run `aws --version` to check yours).

I got this error with the version brew installed (1.10.something), but does work with `aws-cli/1.14.13`. For a Mac, try installing [from here](http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-bundle.html0).

**Comment by ddmkr** [comment]
I had the same issue when configuring the package for someone else. The issue was that the AWS CLI's version was outdated. You should be able to update by doing:
```
pip install awscli --upgrade --user
```

**Comment by filipsch** [comment]
@ddmkr Thanks! @ncarchedi please close if this solves it. Thanks.

**Comment by ncarchedi** [comment]
All set, thanks guys!!

**Comment by vineethvijay** [comment]
Yes true. Didn't work for `aws-cli/1.16.77 Python/2.7.10 Darwin/17.7.0 botocore/1.12.67` -in my mac
Worked for `aws-cli/1.16.119 Python/2.7.5 Linux/3.10.0-957.5.1.el7.x86_64 botocore/1.12.109` - aws linux
